### ISSUE TITLE
What's the difference to git-lfs?

### ISSUE THREAD

**Issue by con-f-use** [jedbrown/git-fat#100]
What's the difference to git-lfs? Sorry for the ignorant question, but you mention to similar projects but not `git-lfs`. Maybe git-lfs and its relation to git-fat should be in the Readme's  "related projects" section.

**Comment by jedbrown** [comment]
git-lfs was created after git-fat. Many people find git-fat simpler, but I unfortunately don't have time to maintain this project and no longer have a need to use it so git-lfs is probably a better choice. (What makes maintenance hard is that people want to make changes that would break backward compatibility, though we don't have great test coverage of that.)

**Comment by con-f-use** [comment]
I feel your pain :grin: 
Maybe just add this answer to the Readme?
