### ISSUE TITLE
rsync exits in Windows mingw

### ISSUE THREAD

**Issue by duanem** [jedbrown/git-fat#40]
I've cobbled together a windows/git/git-fat environment that generally seems to work. However, rsync aborts immediately after it is started by git-fat.

rsync: read error: Connection reset by peer (104)
rsync error: unexplained error (code 255) at /usr/src/rsync/rsync-3.0.8/io.c(760
) [Receiver=3.0.8]

The cobbled together environment is setup as:
1. Install msysgit using option 2 (all executables available from Windows).
2. Install mingw
3. install rsync using mingw-get install msys-rsync
4. Install Python for windows (Python 2.7)
5. Update the Windows system path to include C:\Python27.
6. Add git-fat to a directory on the path (i.e. /bin).

I can run all the pieces separately. Whenever git-fat executes rsync, rsync exits.

I can run manually.
- git fat init
- git fat status > fat-files.txt
- # edit fat-files.txt in order to feed into rsync
- rsync --progress --ignore-existing --files-from=- "--rsh=ssh -l user" path:fat-store/repo/ .git\fat\objects/ < fat-files.txt
- git fat pull

The last command shows rsync aborting, but the python script continues and fixes up all the files.

It seems that many have gone through this situation. I've managed to update for binary files. How can I get rsync to not exit?

**Comment by CzarekTomczak** [comment]
@duanem @piinecone See this comment: https://github.com/jedbrown/git-fat/issues/43#issuecomment-69011567
