### ISSUE TITLE
Where should `.gitattributes` be put?

### ISSUE THREAD

**Issue by pengyu** [jedbrown/git-fat#59]
The README says the following.

`Edit .gitattributes to regard any desired extensions as fat files.`

However, it is not clear where this `.gitattributes` should be put. Is it the git repository on which I want to use `git-fat`? Or it is in my home directory. Can somebody update the README to make it clear? Thanks.

**Comment by HalfVoxel** [comment]
Hi

.gitattributes can be placed in two places. However usually it is just put in the root of the repository.
See http://git-scm.com/book/en/v2/Customizing-Git-Git-Attributes

**Comment by HalfVoxel** [comment]
Created pull #60
