### ISSUE TITLE
git fat pull doesn't work in subdirectories

### ISSUE THREAD

**Issue by jeaye** [jedbrown/git-fat#64]
If I'm in a subdirectory of my git repository and I try to `git fat pull`, the proper files will not be pulled and linked up properly, but no errors are reported. Is this intended behavior? git works the same in any subdirectory of a git repository, always finding the closest `.git` from `.` upward; it would make sense to me that git-fat should do the same.

**Comment by jeaye** [comment]
Any update on this?

**Comment by jedbrown** [comment]
I tried
```
cd sub
echo foo > c.fat
git add c.fat
git commit -am'add c.fat'
cd /path/to/other/clone
git pull
cd sub
git fat pull
```

and there were no errors and I got `c.fat` in that directory. A concrete test case (e.g., add it to `test.sh` or add a new test script) would be helpful.

I try to do basic maintenance on git-fat, but I'm not actually using it in any projects right now and it's hard to prioritize right now with a baby and many work obligations. I'll merge patches that don't break compatibility and are consistent with the scope of the project.

**Comment by jeaye** [comment]
@jedbrown After that `git commit`, did you `git push origin master`? If you did exactly those commands, you'd have nothing to pull, since nothing was pushed.

**Comment by jedbrown** [comment]
The second repo is a direct clone of the first.Please submit a PR with a failing test case.On Jan 20, 2018 14:08, Jeaye Wilkerson <notifications@github.com> wrote:@jedbrown After that git commit, did you git push origin master? If you did exactly those commands, you'd have nothing to pull, since nothing was pushed.

**Comment by jeaye** [comment]
Closing this, since it's apparently not an issue for other folks and I've only been using git lfs these days.
