### ISSUE TITLE
git fat push : 0 files to consider

### ISSUE THREAD

**Issue by cnweibo** [jedbrown/git-fat#66]
@jedbrown : Hello, i have setup everything according to your readme, i use the rsync.
In .gitfat:
[rsync]
remote = 112.124.37.169:/home/gitfat/gitfatlibs
sshuser = gitfat

After I have git add xxx.jpg and commit it, it seems ok.
The .git/fat/objects has one hashed file( I assume this should be the binary image file)
when I run : git fat push, 
it always say: 
gitfat@112.124.37.169's password: 
building file list ... 
0 files to consider
Can you help to figure out what happens here? What is the issue, is it a bug of git-fat itself?
Thanks!

**Comment by jedbrown** [comment]
Please compare to the `test.sh` script in the repository.  I suspect you've missed a step, but if you're still having problems, make a script to reproduce.  (In general, paraphrasing is rarely useful in a bug report and never better than a script that reproduces the problem.)

**Comment by cnweibo** [comment]
Sorry, please close this issue. I figure it out: It is caused by the filter not set.
Since the .gif file i am adding will be filtered by git fat, i set the .png in the .gitattribute file.
It is my configuration issue.
Thanks!
