### ISSUE TITLE
git fat pull tells rsync error

### ISSUE THREAD

**Issue by cnweibo** [jedbrown/git-fat#67]
@jedbrown , Hello, sir,
When I finish mp3 files rsync to server via "git fat push", and then git clone the repo, git fat pull to retrieve the mp3 files, it always say rsync error.
It seems that inconsistent between file server and git-fat. I do not know whether or not it is a git fat bug or not. 
How to locate that problem?
Thanks very much, it has bothered me one day.

"rsync: link_stat "/home/gitfat/gitfatlibs/d6bff0d70b60442d004c0affe6c1ab890615046a" failed: No such file or directory (2)
"
vagrant@homestead:~/kidsit$ git fat pull
root@112.124.37.169's password: 
receiving file list ... 
rsync: link_stat "/home/gitfat/gitfatlibs/d6bff0d70b60442d004c0affe6c1ab890615046a" failed: No such file or directory (2)
rsync: link_stat "/home/gitfat/gitfatlibs/de51a8494180a6db074af2dee2383f0a363c5b08" failed: No such file or directory (2)
rsync: link_stat "/home/gitfat/gitfatlibs/8efe3f44b5143f09ff5cb033bac9aa0895b47364" failed: No such file or directory (2)
rsync: link_stat "/home/gitfat/gitfatlibs/f4b9a411943fe9d920c5d5a56975d12c35928172" failed: No such file or directory (2)
0 files to consider
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1655) [Receiver=3.1.1]

**Comment by jedbrown** [comment]
Those files have not been pushed to that location.  Perhaps you're looking at the wrong host or the path is incorrect.

**Comment by cnweibo** [comment]
I manually remove some above file, it works.
