### ISSUE TITLE
Push to specific rsync folder?

### ISSUE THREAD

**Issue by alexbrodersen** [jedbrown/git-fat#88]
Any way to have git fat push to a folder whose name is relative to the folder name of the git repository?

**Comment by jedbrown** [comment]
If we do
```
git clone repo1 repo2
```
then `repo2/.git/config` contains the absolute path to `repo1`. It sounds like you want `git-fat` to behave differently, keeping a path relative to the root of the repository. That seems to be asking for unintended consequences. I'll close this issue on the assumption that's what you're asking for. If I misunderstood the question or you can show that the behavior you're asking for is in fact well supported by Git, feel free to reopen.
