### ISSUE TITLE
Rewrite History without Git-Fat

### ISSUE THREAD

**Issue by Rocketeer007** [jedbrown/git-fat#99]
For "reasons", my company is trying to move off of git-fat and towards git-lfs.

Both Git-Fat and Git-LFS provide useful documentation on how to rewrite history to make things as if that system had been used since the first commit.  However, I can't figure out a way to rewrite history and replace references with real objects.

I've tried using `filter-branch` with the `--tree-filter` option and removing the `.gitattributes` file, but I guess that git doesn't see that the previously-fat files have changed, so they don't get re-committed.

Any suggestions on how I can proceed?

**Comment by jedbrown** [comment]
Maybe you could share the `filter-branch` command you are using? It sounds like a usage issue.

Honestly, moving to git-lfs is probably a good choice. I haven't used git-fat in my own projects for several years and don't have time to play an active role. I'm glad it continues to work for current users.

**Comment by Rocketeer007** [comment]
My first attempt just removed the `.gitattributes` file, and attempted to restore the fat files.  However, the index didn't seem to get updated with the original files, so I still just had the hashes in the repo:
```
git filter-branch --all --tree-filter 'git fat pull; rm -f .gitattributes' HEAD
```

After a bit more research last night, I came up with this command, which appears to have done what I wanted.  I had to change from removing the `.gitattributes` to just emptying it as otherwise something complained about a missing file:
```
git filter-branch --tree-filter 'git fat pull; echo > .gitattributes ; git rm -f .gitfat ; git add --renormalize .' HEAD --all
```

However, I think I may have done something wrong with this command, because I don't seem to have correctly updated all my branches; when I pushed back to the remote, only the "master" branch was updated.  I'm only doing this on a backup copy of the repo, so no harm done yet :-) 

Do I need to checkout each branch locally before running this command, or is there a trick to push all updated refs somehow? I'm way out of my depth here :/

**Comment by Rocketeer007** [comment]
So, for future readers, here was my final solution to replace Git-fat with Git-LFS.  It might be possible to do it better - I don't know enough about either system to say how though.

One undesired artifact remains - I got a "HEAD" branch created on my remote at the end, which I had to remove through the GitLab UI...

```
# Update the local repo with all branches and tags
git pull
git fetch --all
git fetch --tags
git fat pull

# Replace Git-FAT references with actual files, on all branches and tags
git filter-branch --tree-filter 'git fat pull; echo > .gitattributes ; git rm -f .gitfat ; git add --renormalize .' -- --all

# Remove the backup created by tree-filter
rm -Rf .git/refs/original

# Create local tracking branches for each remote branch
for branch in `git branch -a | grep remotes | grep -v HEAD | grep -v master `; do
   git branch --track ${branch#remotes/origin/} $branch
done

# Migrate all local branches to Git-LFS (only for *.jar and *.gz files here)
git lfs migrate import --everything --include="*.jar,*.gz"

# Cleanup locally
git reflog expire --expire-unreachable=now --all
git gc --prune=now

# Push all changes to the remote
git push -f --atomic
git push --prune origin "+refs/remotes/origin/*:refs/heads/*" "+refs/tags/*:refs/tags/*"
```

**Comment by jedbrown** [comment]
Thanks for this advice. I'll close this issue since it sounds like it's resolved.
